### ISSUE TITLE
Wait-For-It Not Working

### ISSUE THREAD

**Issue by ghost** [oliversturm/demo-xaf-docker#1]
When following the tutorial located [here](https://community.devexpress.com/blogs/news/archive/2023/04/06/develop-a-devexpress-xaf-and-web-api-solution-in-docker.aspx) and running the command `docker compose up --build -d` and error is received when debugging the container(s). It appears that the `wait-for-it` command is invalid in my case.

**Comment by oliversturm** [comment]
Thanks for reporting this. I just tried to build the containers from scratch and I'm afraid I can't reproduce the problem. 

Pretty strange thing, since the command is expected to be available in the container, and the `Dockerfile` includes the line `RUN apt-get install -y wait-for-it ...` just above the point where the command is used.

Can you please clarify your environment? Are you using the repo content unchanged? Which platform, Docker versions etc are you running on? Can you post the error output you're receiving, or better yet the entire output from the command `docker compose up --build -d`?

I'll try my best to find this issue if I can reproduce it.

**Comment by oliversturm** [comment]
I found the problem and it's totally my fault -- apologies! The issue was that the `Dockerfile` included in the blog post didn't include the item `wait-for-it` in the `apt-get` line. I fixed this now, and to be clear, this is the line how it should be:

```dockerfile
RUN apt-get install -y wait-for-it libc6 libicu-dev libfontconfig1 libgdiplus
```

Again, thank you for the report!
